### ISSUE TITLE
dead

### ISSUE THREAD

**Issue by ahmedtds** [caffeinewriter/twitch-search#1]
this site was exactly what i was looking for but looks like it's dead. it doesn't return search results for anything. i'm sad.

**Comment by caffeinewriter** [comment]
Thanks for the heads up @ahmedtds I'll take a look and see if I can isolate the issue.

**Comment by ahmedtds** [comment]
Wow thanks for a super quick answer. I'm not an expert on this stuff but I think twitch api was changed a while ago. They don't permit anon requests anymore or something like that. Need an auth or clientid or something like that if i'm not wrong. Maybe that's the issue.

**Comment by caffeinewriter** [comment]
Yeah, that's the issue @ahmedtds. Anon requests still worked when I put this together, but they must have turned them off today. Set it up to use the client ID already included, so it should work now. Happy searching!
