### ISSUE TITLE
Allow to save search to favorites

### ISSUE THREAD

**Issue by zoum26** [caffeinewriter/twitch-search#5]
I wish we could save search as a favorite in my browser or in another way so that when i open the website it goes right away to what i want instead of having to type it.

**Comment by caffeinewriter** [comment]
I may be able to add this using localstorage or something similar. :) I'll leave this open until I do add it. 

Also, the app now supports routing, so you can bookmark your favorite searches.

**Comment by caffeinewriter** [comment]
I'm actually going to go ahead and close this. I don't think I could add better functionality than bookmarks that would work in a useful way. If you have suggestions, feel free to open another issue, or comment here.
