### ISSUE TITLE
SearchTwitch needs to be updated to v5 API.

### ISSUE THREAD

**Issue by PachiMc** [caffeinewriter/twitch-search#7]
maybe twitch olld api?

**Comment by caffeinewriter** [comment]
Hey there, you're correct. It's presently not updated to use the new API. I'm working on it, but unfortunately the whole site is in pretty dire need of a rewrite. I'll update this issue once the new site is live. :)

**Comment by caffeinewriter** [comment]
I apologize for the delay, but SearchTwitch has finally been updated! The site should be working again. It's now deployed elsewhere, so some DNS changes may take up to 48 hours to propagate. :raised_hands:
